name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
      
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4

    - name: build
      run: make platform-all
